In [1]:
import pandas as pd 
df=pd.read_excel('./카테고리재분류3.xlsx')
df[['distance','walking_time']]=0
df=df.rename(columns={'category':'category_all'})
df.to_excel('카테고리재분류3.xlsx',index=False)

In [2]:
pd.set_option('display.max_rows',None)
df['category_2'].value_counts()

category_2
육류,고기       262
치킨          206
해물,생선       167
고기구이        166
백반/가정식      157
분식          131
중국요리         99
한식면요리        78
국밥           76
파스타/스테이크     74
초밥/회         61
탕/찌개         58
족발/보쌈        48
순대           47
일식일반         46
돈까스          43
마라/양꼬치       42
떡볶이          40
햄버거          39
양식일반         30
고기요리         25
전/민속주점       20
간편식/덮밥       18
이탈리안         18
중식           18
죽            18
제과,베이커리      18
샤브샤브         17
찌개/탕         16
돈까스,우동       15
면요리(일식)      15
국수           14
샐러드          14
닭강정          13
베트남음식        11
양꼬치          10
일본식라면         9
멕시칸,브라질       9
해물요리/찜        9
컵밥            9
사철탕,영양탕       9
간식            8
냉면            8
초밥,롤          7
한식뷔페          7
태국음식          7
찌개/조림         7
찌개,전골         7
탕             6
동남아음식         6
도시락           6
두부전문점         6
건강식/정식        5
감자탕           5
한솥도시락         5
싸다김밥          4
토스트           4
쌈밥            4
피자            4
구내식당          4
식품            4
일식집           4
포케올데이         3
등촌샤브칼국수       3
김가네           3
본도시락          3
백소정           3
해장국           3
슬로우캘리         3
인도음식          3
만두            3
퓨전요리          3
타코야끼          2
퓨전일식          2
설렁탕           2
채선당           2
고기뷔페          2
뽕잎사랑          2
애슐리           2
장호덕손만두        2
단체,협회         2
한정식           2
전문대행          2
분식/면요리        2
배달도시락         2
도넛            2
기사식당          2
돈까스/함박        2
덮밥/카레         2
한우            1
참치회           1
틈새라면          1
갱상도           1
해물요리          1
편편집           1
치킨/라이스        1
행컵            1
스포츠시설         1
퓨전한식          1
곰탕            1
튀김/분식         1
학원            1
정보통신          1
돼지고기구이        1
스페인음식         1
돼지게티          1
아비꼬           1
패밀리레스토랑       1
면식당           1
해산물           1
Name: count, dtype: int64

In [3]:
df[df['category_2'] == '일식일반']

,name,address,category_all,latitude,longitude,category_1,category_2,distance,walking_time
161,고씨네 신림대학동점,서울 관악구 신림동 1515-4,음식점 > 일식,37.470458,126.936401,일식,일식일반,0,0
216,구루메키친,서울 관악구 봉천동 1620-30,음식점 > 일식,37.477953,126.958039,일식,일식일반,0,0
260,규이치,서울 관악구 봉천동 870-13,음식점 > 일식,37.481744,126.951451,일식,일식일반,0,0
426,당당,서울 관악구 남현동 1056-31,음식점 > 일식,37.476107,126.976133,일식,일식일반,0,0
466,덮스테이,서울 관악구 봉천동 1597-7,음식점 > 일식,37.478090,126.952740,일식,일식일반,0,0
480,도쿄시장 신림점,서울 관악구 신림동 1639-30,음식점 > 일식,37.483359,126.928412,일식,일식일반,0,0
505,동경산책,서울 관악구 봉천동 1604-8,음식점 > 일식,37.478870,126.954200,일식,일식일반,0,0
636,마츠,서울 관악구 신림동 1460-1,음식점 > 일식,37.486454,126.926089,일식,일식일반,0,0
696,멘부리 신림점,서울 관악구 봉천동 928-5,음식점 > 일식,37.481550,126.942508,일식,일식일반,0,0
934,봉천다찌,서울 관악구 봉천동 1612-2,음식점 > 일식,37.479396,126.955764,일식,일식일반,0,0
1008,사케바미유,서울 관악구 봉천동 1608-4,음식점 > 일식,37.476641,126.954739,일식,일식일반,0,0
1009,사케앤살몬,서울 관악구 봉천동 1619-9,음식점 > 일식,37.477924,126.956632,일식,일식일반,0,0
1040,삿뽀로,서울 관악구 봉천동 729-22,음식점 > 일식,37.490398,126.924769,일식,일식일반,0,0
1151,소미당,서울 관악구 신림동 1537-7,음식점 > 일식,37.468951,126.936526,일식,일식일반,0,0
1158,소쿠리,서울 관악구 봉천동 28-64,음식점 > 일식,37.483350,126.956390,일식,일식일반,0,0
1230,스아게 샤로수길,서울 관악구 봉천동 1599-4,음식점 > 일식,37.479204,126.953544,일식,일식일반,0,0
1231,스윗보울,서울 관악구 신림동 1636-54,음식점 > 일식,37.480290,126.928365,일식,일식일반,0,0
1232,스타동(봉천점),서울 관악구 봉천동 930-1,음식점 > 일식,37.482080,126.941809,일식,일식일반,0,0
1323,심야식당 무타,서울 관악구 신림동 1417-34,음식점 > 일식,37.486822,126.930784,일식,일식일반,0,0
1357,아자스,서울 관악구 신림동 1575-1,음식점 > 일식,37.482107,126.920391,일식,일식일반,0,0
1376,앤미,서울 관악구 봉천동 1610-24,음식점 > 일식,37.477843,126.955073,일식,일식일반,0,0
1378,야나기,서울 관악구 봉천동 1611-24,음식점 > 일식,37.479469,126.955294,일식,일식일반,0,0
1381,야키니쿠 리,서울 관악구 봉천동 1664-16,음식점 > 일식,37.479300,126.957279,일식,일식일반,0,0
1382,야키토리 리,서울 관악구 봉천동 1664-16,음식점 > 일식,37.479288,126.957293,일식,일식일반,0,0
1383,야키토리 미치,서울 관악구 봉천동 1613-5,음식점 > 일식,37.478262,126.955932,일식,일식일반,0,0
1506,오지,서울 관악구 봉천동 1620-42,음식점 > 일식,37.477872,126.958237,일식,일식일반,0,0
1551,요술사,서울 관악구 봉천동 1621-21,음식점 > 일식,37.477774,126.956879,일식,일식일반,0,0
1561,우나기 쿄다이,서울 관악구 봉천동 895-25,음식점 > 일식,37.481102,126.947065,일식,일식일반,0,0
1635,은행골 서울대입구역점,서울 관악구 봉천동 857-5,음식점 > 일식,37.480643,126.952931,일식,일식일반,0,0
1667,이자와 샤로수길점,서울 관악구 봉천동 1604-6,음식점 > 일식,37.478945,126.953983,일식,일식일반,0,0
1674,이쿠,서울 관악구 봉천동 196-32,음식점 > 일식,37.474601,126.963924,일식,일식일반,0,0
1829,주수,서울 관악구 봉천동 1612-45,음식점 > 일식,37.478470,126.956871,일식,일식일반,0,0
1915,창운 사공하나,서울 관악구 봉천동 924-19,음식점 > 일식,37.483209,126.944549,일식,일식일반,0,0
2011,카카라,서울 관악구 신림동 519-9,음식점 > 일식,37.484866,126.913394,일식,일식일반,0,0
2041,키요이 스키야키,서울 관악구 봉천동 1620-5,음식점 > 일식,37.478457,126.957095,일식,일식일반,0,0
2043,킷사서울,서울 관악구 봉천동 1603-3,음식점 > 일식,37.479195,126.953759,일식,일식일반,0,0
2048,타마,서울 관악구 신림동 537-43,음식점 > 일식,37.483064,126.913046,일식,일식일반,0,0
2072,테라다식당 서울대입구점,서울 관악구 봉천동 1612-27,음식점 > 일식,37.478652,126.956053,일식,일식일반,0,0
2076,텐동요츠야,서울 관악구 봉천동 1612-40,음식점 > 일식,37.478439,126.956552,일식,일식일반,0,0
2144,푸른연어,서울 관악구 봉천동 735-6,음식점 > 일식,37.490795,126.926546,일식,일식일반,0,0
2229,한술더,서울 관악구 봉천동 921-10,음식점 > 일식,37.481070,126.944142,일식,일식일반,0,0
2292,호랑이면,서울 관악구 봉천동 1621-1,음식점 > 일식,37.478129,126.956912,일식,일식일반,0,0
2304,혼맛,서울 관악구 신림동 1423-21,음식점 > 일식,37.485857,126.930313,일식,일식일반,0,0
2305,혼야키,서울 관악구 봉천동 56-110,음식점 > 일식,37.483284,126.953206,일식,일식일반,0,0
2361,후추네,서울 관악구 봉천동 1620-21,음식점 > 일식,37.478213,126.957317,일식,일식일반,0,0
2377,히토스지,서울 관악구 봉천동 464-17,음식점 > 일식,37.486894,126.948338,일식,일식일반,0,0

In [4]:
df.loc[df['name'].str.contains('돼지게티'), ['category_1', 'category_2']] = ['양식', '파스타']
print(df[df['name'].str.contains('룸타이')][['name', 'category_1', 'category_2']])

Empty DataFrame
Columns: [name, category_1, category_2]
Index: []

In [5]:
def refine_japanese_general(row):
    if row['category_2'] == '일식일반':
        name = str(row['name']).upper()
        
        # 1. 초밥/스시/회 전문
        if any(k in name for k in ['스시', 'SUSHI', '은행골', '사케앤살몬', '연어', '푸른연어', '혼맛']):
            return '초밥/스시'
            
        # 2. 덮밥/돈부리 전문
        if any(k in name for k in ['덮스테이', '멘부리', '스타동', '소미당', '앤미']):
            return '일식덮밥'
            
        # 3. 라멘/우동/소바 전문 (면요리)
        if any(k in name for k in ['호랑이면', '히토스지', '창운', '국수']):
            return '일식면요리'
            
        # 4. 돈까스/튀김 전문
        if any(k in name for k in ['텐동', '요츠야', '카츠', '이자와', '규카츠', '후추네']):
            return '돈까스/튀김'
            
        # 5. 야키토리/이자카야/술집 (저녁 위주)
        # 사장님, '술집'은 다 빼기로 했지만 '음식점'으로 분류된 이자카야는 일단 살려둡니다.
        if any(k in name for k in ['야키토리', '야나기', '야키니쿠', '마츠', '사케바', '이자카야', '봉천다찌', '요술사']):
            return '일식주점'
            
        # 6. 일본식 카레/스키야키 등 기타 일식
        if any(k in name for k in ['고씨네', '카레', '스키야키', '키요이', '스아게', '당당']):
            return '기타일식'

    return row['category_2']

# 적용!
df['category_2'] = df.apply(refine_japanese_general, axis=1)

In [ ]:
def refine_japanese_v2(row):
    if row['category_2'] == '일식일반':
        name = str(row['name'])
        
        # 1. 일식 덮밥/가정식 (샤로수길 핫플 위주)
        if any(k in name for k in ['킷사서울', '동경산책', '소쿠리', '테라다식당', '한술더']):
            return '일식덮밥/가정식'
            
        # 2. 이자카야/심야식당 (주점 성격이 강한 곳)
        if any(k in name for k in ['심야식당', '구루메키친', '이쿠', '주수', '아자스', '도쿄시장', '오지']):
            return '일식주점'
            
        # 3. 야키니쿠/야키토리/고기류
        if any(k in name for k in ['규이치', '혼야키', '타마']): # 타마는 오코노미야키/철판요리
            return '일식구이/철판'
            
        # 4. 장어/회 전문
        if any(k in name for k in ['우나기', '삿뽀로']):
            return '회/일식코스'

        # 5. 기타 특색 메뉴
        if '스윗보울' in name: return '샐러드/포케' # 일식 베이스 포케집인 경우
        if '카카라' in name: return '일식카레'

    return row['category_2']

# 적용
df['category_2'] = df.apply(refine_japanese_v2, axis=1)

,name,address,category_all,latitude,longitude,category_1,category_2,distance,walking_time
161,고씨네 신림대학동점,서울 관악구 신림동 1515-4,음식점 > 일식,37.470458,126.936401,일식,기타일식,0,0
426,당당,서울 관악구 남현동 1056-31,음식점 > 일식,37.476107,126.976133,일식,기타일식,0,0
1230,스아게 샤로수길,서울 관악구 봉천동 1599-4,음식점 > 일식,37.479204,126.953544,일식,기타일식,0,0
2041,키요이 스키야키,서울 관악구 봉천동 1620-5,음식점 > 일식,37.478457,126.957095,일식,기타일식,0,0

In [12]:
df[df['name'] == '아비꼬 서울대입구역점']

,name,address,category_all,latitude,longitude,category_1,category_2,distance,walking_time
1353,아비꼬 서울대입구역점,서울 관악구 봉천동 1601-1,음식점 > 퓨전요리 > 아비꼬,37.480393,126.954324,퓨전요리,아비꼬,0,0

In [13]:
df['category_2'].value_counts()

category_2
육류,고기       262
치킨          206
해물,생선       167
고기구이        166
백반/가정식      157
분식          131
중국요리         99
한식면요리        78
국밥           76
파스타/스테이크     74
초밥/회         61
탕/찌개         58
족발/보쌈        48
순대           47
돈까스          43
마라/양꼬치       42
떡볶이          40
햄버거          39
양식일반         30
고기요리         25
전/민속주점       20
간편식/덮밥       18
중식           18
죽            18
제과,베이커리      18
이탈리안         18
샤브샤브         17
찌개/탕         16
면요리(일식)      15
일식주점         15
돈까스,우동       15
샐러드          14
국수           14
닭강정          13
베트남음식        11
양꼬치          10
일본식라면         9
사철탕,영양탕       9
해물요리/찜        9
컵밥            9
멕시칸,브라질       9
간식            8
냉면            8
태국음식          7
찌개/조림         7
찌개,전골         7
한식뷔페          7
초밥,롤          7
동남아음식         6
도시락           6
두부전문점         6
탕             6
건강식/정식        5
일식덮밥/가정식      5
일식덮밥          5
한솥도시락         5
감자탕           5
식품            4
초밥/스시         4
쌈밥            4
싸다김밥          4
토스트           4
일식집           4
구내식당          4
피자            4
기타일식          4
슬로우캘리         3
해장국           3
본도시락          3
백소정           3
퓨전요리          3
일식구이/철판       3
인도음식          3
만두            3
돈까스/튀김        3
일식면요리         3
김가네           3
등촌샤브칼국수       3
포케올데이         3
회/일식코스        2
애슐리           2
장호덕손만두        2
전문대행          2
고기뷔페          2
타코야끼          2
퓨전일식          2
채선당           2
한정식           2
설렁탕           2
단체,협회         2
도넛            2
배달도시락         2
분식/면요리        2
덮밥/카레         2
뽕잎사랑          2
돈까스/함박        2
기사식당          2
편편집           1
해물요리          1
치킨/라이스        1
틈새라면          1
참치회           1
한우            1
스포츠시설         1
튀김/분식         1
행컵            1
일식카레          1
학원            1
곰탕            1
패밀리레스토랑       1
면식당           1
정보통신          1
돼지고기구이        1
스페인음식         1
아비꼬           1
퓨전한식          1
갱상도           1
파스타           1
샐러드/포케        1
해산물           1
Name: count, dtype: int64

In [ ]:
before_count = len(df)
df = df[df['category_2'] != '일식주점']
after_count = len(df)

print(f"일식주점 {before_count - after_count}개 삭제 완료!")

df.loc[df['name'].str.contains('고씨네', na=False), 'category_2'] = '일식카레'

print("\n변경 후 '고씨네' 상태:")
print(df[df['name'].str.contains('고씨네')][['name', 'category_2']])

일식주점 15개 삭제 완료!

변경 후 '고씨네' 상태:
           name category_2
161  고씨네 신림대학동점       일식카레

In [15]:
df.to_excel('카테고리_재분류4.xlsx')